### PR TITLE
Issue/116

### LINKED ISSUE #116: [validation] JavaScript validation fails.
with respect to [PR 115](https://github.com/openwisp/django-netjsonconfig/pull/115/commits/78380e62d8c942ec84ce5605ad88b1687dad00af), valid default values for variables can be validated with the schema backend. Even though the schema validates the data, the JavaScript don't still validated the data entered. It shows input error.
**How to reproduce the bug**
 do the following in advance mode and hit the exit button, then look at the error message at the `mac_address` field.
{
    "interfaces": [
        {
            "type": "ethernet",
            "disabled": false,
            "mac": "{{ mac_address }}",
            "mtu": 1500,
            "addresses": [],
            "name": "eth0",
            "autostart": true,
            "network": ""
        }
    ]
}
with these defaults:

{
    "mac_address": "00-11-22-33-44-56"
}

### PR DESCRIPTION
**Pull request by NoumbissiValere**
[validation] JavaScript validation fails #116

Replace the variables with default values
before widgets validation in order to make
the test pass with valid default values.

Fixes #116

### CODE REVIEW

**Comment by NoumbissiValere** [comment]
@nemesisdesign Please can you review this when you have time? Thanks

File: django_netjsonconfig/static/django-netjsonconfig/js/lib/jsonschema-ui.js [hunk 1]
```diff
@@ -1,9 +1,3313 @@
...
...psed=!1,this.toggle_button=this.getButton("","collapse",this.translate("button_collapse")),this.title_controls.appendChild(this.toggle_button);var b=a.row_holder.style.display,c=a.controls.style.display;this.toggle_button.addEventListener("click",function(d){d.preventDefault(),d.stopPropagation(),a.collapsed?(a.collapsed=!1,a.panel&&(a.panel.style.display=""),a.row_holder.style.display=b,a.tabs_holder&&(a.tabs_holder.style.display=""),a.controls.style.display=c,a.setButtonText(this,"","collapse",a.translate("button_collapse"))):(a.collapsed=!0,a.row_holder.style.display="none",a.tabs_holder&&(a.tabs_holder.style.display="none"),a.controls.style.display="none",a.panel&&(a.panel.style.display="none"),a.setButtonText(this,"","expand",a.translate("button_expand")))}),this.options.collapsed&&e(this.toggle_button,"click"),this.schema.options&&"undefined"!=typeof this.schema.options.disable_collapse?this.schema.options.disable_collapse&&(this.toggle_button.style.display="none"):this.jsoneditor.options.disable_collapse&&(this.toggle_button.style.display="none"),this.add_row_button=this.getButton(this.getItemTitle(),"add",this.translate("button_add_row_title",[this.getItemTitle()])),this.ad
```
Comment (NoumbissiValere) [inline django_netjsonconfig/static/django-netjsonconfig/js/lib/jsonschema-ui.js]: change to review

**Comment by NoumbissiValere** [comment]
The files were not formatted and thus difficult to debug. so i used `atom-beautify` to format it so as to easily debug. so some of the changes might not be important. don't know how to mark the sections which are important so you just review that area.

**Comment by NoumbissiValere** [comment]
@nemesisdesign I think the validation is ok now. please can you review it? thanks

File: django_netjsonconfig/static/django-netjsonconfig/js/widget.js [hunk 2]
```diff
@@ -160,6 +192,19 @@
             }
         });
 
+        //trigger schema-data validation on default values change
```
Comment (nemesisdesign) [inline django_netjsonconfig/static/django-netjsonconfig/js/widget.js]: leave one space after the `//`

**Comment by dwang** [comment]
Hi @nemesisdesign, I also get the same error.

image

Tested on `Google Chrome Version 75.0.3770.90 (Official Build) (64-bit)`

It looks like the relevant lines are 
```js
	  try {
		  context = JSON.parse(document.getElementById('id_default_values').value);
	  } catch(e) {
		  context = JSON.parse(document.getElementById('id_config-0-context').value);
	  }
```
since it errors when the `<textarea>` is empty and there is no JSON to parse.

**Comment by nemesisdesign** [comment]
Thanks @dwang for your check, it's very useful.

File: django_netjsonconfig/static/django-netjsonconfig/js/widget.js [hunk 3]
```diff
@@ -191,6 +192,19 @@
...
+        try{
+            default_values = $('#id_default_values');
+        } catch(e) {
+            default_values = $('#id_config-0-context');
```
Comment (nemesisdesign) [inline django_netjsonconfig/static/django-netjsonconfig/js/widget.js]: let's change this try/catch block.

You should do something like:

```javascript
var contextField = $('#id_config-0-context') || $('#id_default_values');
if (contextField) {
    contextField.on('change', function() {
        // ...
    }
}
```

File: django_netjsonconfig/api/generics.py [hunk 4]
```diff
@@ -10,7 +10,7 @@ class BaseSearchTemplate(ListAPIView):
     def get_queryset(self):
         name = self.request.GET.get('name', None)
         des = self.request.GET.get('des', None)
-        temp = self.template_model.filter(sharing='public')
+        temp = self.template_model.objects.filter(sharing='public')
```
Comment (nemesisdesign) [inline django_netjsonconfig/api/generics.py]: I think this commit should not be here, please remove that change from the PR, I suggest to squash the commits and remove this change (it may conflict with the other PR as well).

**Comment by NoumbissiValere** [comment]
thanks @nemesisdesign and @dwang . Will work on the changes

**Comment by NoumbissiValere** [comment]
@nemesisdesign Please can you review this? travis is failing because of a bug in a merge branch. 
I will create an issue for this and send a PR now so that it can be merged and i rebase this branch for clean merge.

File: django_netjsonconfig/static/django-netjsonconfig/js/lib/jsonschema-ui.js [hunk 5]
```diff
@@ -1,9 +1,3319 @@
...
```
Comment (nemesisdesign) [inline django_netjsonconfig/static/django-netjsonconfig/js/lib/jsonschema-ui.js]: why is this javascript being expanded? I don't see this change as necessary, what brought you to do this?

File: django_netjsonconfig/static/django-netjsonconfig/js/lib/advanced-mode.js [hunk 6]
```diff
@@ -16298,11 +16322,24 @@ return /******/ (function(modules) { // webpackBootstrap
 	    this.content.style.paddingBottom = '';
 	  }
 
-	  var doValidate = false;
-	  var errors = [];
-	  var json;
+	  var doValidate = false,
+	  	  errors = [],
```
Comment (nemesisdesign) [inline django_netjsonconfig/static/django-netjsonconfig/js/lib/advanced-mode.js]: indentation is not right

File: django_netjsonconfig/static/django-netjsonconfig/js/lib/advanced-mode.js [hunk 7]
```diff
@@ -16298,11 +16322,24 @@ return /******/ (function(modules) { // webpackBootstrap
...
+	      json,
+		  value,
```
Comment (nemesisdesign) [inline django_netjsonconfig/static/django-netjsonconfig/js/lib/advanced-mode.js]: indentation is not right

File: django_netjsonconfig/static/django-netjsonconfig/js/widget.js [hunk 8]
```diff
@@ -93,13 +93,20 @@
...
             context = {},
+            value,
             data,
             cleanedData;
         try {
             try {
-                context = JSON.parse($('#id_default_values').val());
+                value = $('#id_default_values').val();
+                if(value){
+                    context = JSON.parse(value);
```
Comment (nemesisdesign) [inline django_netjsonconfig/static/django-netjsonconfig/js/widget.js]: the indentation of this whole nested try/catch block is very messy and I don't understand what is going on: I don't understand if all the blocks have the closing `}` or not, please keep the indentation clean and the code readable

File: django_netjsonconfig/static/django-netjsonconfig/js/lib/jsonschema-ui.js (hunk 5 above)
Comment (NoumbissiValere) [reply django_netjsonconfig/static/django-netjsonconfig/js/lib/jsonschema-ui.js]: I expanded it because i wanted to understand the code so as to understand what was actually happening.

**Comment by NoumbissiValere** [comment]
@nemesisdesign I have optimized the code. please can you review? i will be glad to correct errors if any. thanks.

**Comment by NoumbissiValere** [comment]
Yes i don't get any errors in the console log. My console log is clean.

**Comment by NoumbissiValere** [comment]
> The code looks better but I still get JS errors when loading the edit or add device page.
> 
> Don't you notice JS errors in the console?
Here is my add device page

Screenshot from 2019-06-23 20-42-26

**Comment by NoumbissiValere** [comment]
Here is my edit device page
Screenshot from 2019-06-23 20-46-11

**Comment by oltarzewskik** [comment]
@NoumbissiValere @nemesisdesign I don't see any error too:
Screenshot at 2019-06-25 14-10-51

**Comment by okraits** [comment]
In firefox I get a warning which says that `window.controllers/Controllers` shouldn't be used anymore, in https://github.com/NoumbissiValere/django-netjsonconfig/blob/issue/116/django_netjsonconfig/static/django-netjsonconfig/js/lib/advanced-mode.js. But I don't get any errors.
